# -*- coding: utf-8 -*-
"""Data_Gathering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kuAfJl1LJVGkE0bJ4Ya6CBvkd4QprxuQ

#CSV Data format
"""

import numpy as np
import pandas as pd

"""#Opening a file from a local csv"""

df=pd.read_csv('aug_train.csv')

df

"""#Opening a file from a csv file from a url

---


"""

import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

"""#Opening a TSV file"""

df=pd.read_csv('iris.tsv',sep='\t',names=['p1','p2','p3','p4','Species'])

df

"""#Index Col Parameter"""

pd.read_csv('aug_train.csv',index_col='enrollee_id')

"""#Header Parameter ,when the header becomes the first row how to handle it is :"""

pd.read_csv('aug_train.csv')

pd.read_csv('aug_train.csv',header=1)

"""#Use cols Parameter"""

pd.read_csv('aug_train.csv',usecols=['enrollee_id','gender','education_level'])

"""#Squeeze Parameter its pandas series object
# The squeze parameter is depreciated.
"""

pd.read_csv('aug_train.csv',usecols=['gender'])['gender']

"""#Skiprows Nrows Parameter"""

pd.read_csv('aug_train.csv',skiprows=[0,1])

"""#Nrows is used to load a pirticular set of rows into the memory"""

pd.read_csv('aug_train.csv',nrows=100)

"""#Encoding Parameter"""

pd.read_csv('zomato.csv',encoding='latin-1')

"""#Skip Bad lines
#the latest non depreciated functiion is on_bad_lines='skip'
"""

pd.read_csv('BX-Books.csv', sep=';', encoding="latin-1", on_bad_lines='skip')

"""#dTypes parameter"""

pd.read_csv('aug_train.csv',dtype={'target':int}).info()

"""#Handling Dates


"""

ipl=pd.read_csv('ipl.csv',parse_dates=['date'])

ipl.info()

"""#Converters"""

pd.read_csv('ipl.csv')

def rename(name):
  if name=='Royal Challengers Bangalore':
    return 'RCB'
  else:
    return name

pd.read_csv('ipl.csv',converters={'team2':rename})

"""#na values parameter"""

pd.read_csv('aug_train.csv',na_values=['Male'])

"""#Loading a huge dataset in chunks"""

dfs=pd.read_csv('aug_train.csv',chunksize=5000)

for chunks in dfs:
  print(chunks.shape)

