# -*- coding: utf-8 -*-
"""End_to_end_toy_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ovd9Q2D0SyE3n2sOl8RQGYJTjPZCyfS7

#**Primary steps in ML Life cycle**

#1 Preprocessing + EDA +Feature Selection
#2 Extracting input and output cells
#3 Scaling of values
#4 Train test split
#5 Training the model
#6 Evaluation nof the model
#7 Deployment of the model

# Importing required libraries
"""

import numpy as np
import pandas as pd

"""#Using the read.csv function from pandas to construct a dataframe"""

df=pd.read_csv('/content/placement.csv')

"""#Printing the dataframe"""

df.head()

"""#df.info gives the d type for each columns in the dataframe"""

df.info()

"""#A small data preprocessing step"""

df=df.iloc[:,1:]
df

"""#Importing a data visualisation library pyplot"""

import matplotlib.pyplot as plt

plt.scatter(df['cgpa'],df['iq'],c=df['placement'])

"""#Extracting input and output cells"""

X=df.iloc[:,0:2]
Y=df.iloc[:,-1]

"""#Input"""

X

"""#Output"""

Y

"""#Train Test split"""

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1)

X_train

X_test

Y_train

Y_test

"""#Scaling of Data"""

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

#model training
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,Y_train)

#model eval
y_pred=model.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

#trend followed by the model
from mlxtend.plotting import plot_decision_regions
plot_decision_regions(X_train,y=Y_train.values,clf=model)

import pickle
pickle.dump(model,open('model.pkl','wb'))